// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/evidenceledger/gosiop2/ent/account"
	"github.com/evidenceledger/gosiop2/ent/privatekey"
	"github.com/evidenceledger/gosiop2/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[0].Descriptor()
	// account.NameValidator is a validator for the "name" field. It is called by the builders before save.
	account.NameValidator = accountDescName.Validators[0].(func(string) error)
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[1].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountFields[2].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	privatekeyFields := schema.PrivateKey{}.Fields()
	_ = privatekeyFields
	// privatekeyDescPrivate is the schema descriptor for private field.
	privatekeyDescPrivate := privatekeyFields[3].Descriptor()
	// privatekey.DefaultPrivate holds the default value on creation for the private field.
	privatekey.DefaultPrivate = privatekeyDescPrivate.Default.(bool)
	// privatekeyDescCreatedAt is the schema descriptor for created_at field.
	privatekeyDescCreatedAt := privatekeyFields[5].Descriptor()
	// privatekey.DefaultCreatedAt holds the default value on creation for the created_at field.
	privatekey.DefaultCreatedAt = privatekeyDescCreatedAt.Default.(func() time.Time)
	// privatekeyDescUpdatedAt is the schema descriptor for updated_at field.
	privatekeyDescUpdatedAt := privatekeyFields[6].Descriptor()
	// privatekey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	privatekey.DefaultUpdatedAt = privatekeyDescUpdatedAt.Default.(func() time.Time)
}
