// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/evidenceledger/gosiop2/ent/account"
	"github.com/evidenceledger/gosiop2/ent/credential"
	"github.com/evidenceledger/gosiop2/ent/privatekey"
	"github.com/evidenceledger/gosiop2/ent/publickey"
	"github.com/evidenceledger/gosiop2/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[0].Descriptor()
	// account.NameValidator is a validator for the "name" field. It is called by the builders before save.
	account.NameValidator = accountDescName.Validators[0].(func(string) error)
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[1].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountFields[2].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	credentialFields := schema.Credential{}.Fields()
	_ = credentialFields
	// credentialDescType is the schema descriptor for type field.
	credentialDescType := credentialFields[1].Descriptor()
	// credential.DefaultType holds the default value on creation for the type field.
	credential.DefaultType = credentialDescType.Default.(string)
	// credentialDescCreatedAt is the schema descriptor for created_at field.
	credentialDescCreatedAt := credentialFields[3].Descriptor()
	// credential.DefaultCreatedAt holds the default value on creation for the created_at field.
	credential.DefaultCreatedAt = credentialDescCreatedAt.Default.(func() time.Time)
	// credentialDescUpdatedAt is the schema descriptor for updated_at field.
	credentialDescUpdatedAt := credentialFields[4].Descriptor()
	// credential.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	credential.DefaultUpdatedAt = credentialDescUpdatedAt.Default.(func() time.Time)
	privatekeyFields := schema.PrivateKey{}.Fields()
	_ = privatekeyFields
	// privatekeyDescCreatedAt is the schema descriptor for created_at field.
	privatekeyDescCreatedAt := privatekeyFields[4].Descriptor()
	// privatekey.DefaultCreatedAt holds the default value on creation for the created_at field.
	privatekey.DefaultCreatedAt = privatekeyDescCreatedAt.Default.(func() time.Time)
	// privatekeyDescUpdatedAt is the schema descriptor for updated_at field.
	privatekeyDescUpdatedAt := privatekeyFields[5].Descriptor()
	// privatekey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	privatekey.DefaultUpdatedAt = privatekeyDescUpdatedAt.Default.(func() time.Time)
	publickeyFields := schema.PublicKey{}.Fields()
	_ = publickeyFields
	// publickeyDescCreatedAt is the schema descriptor for created_at field.
	publickeyDescCreatedAt := publickeyFields[4].Descriptor()
	// publickey.DefaultCreatedAt holds the default value on creation for the created_at field.
	publickey.DefaultCreatedAt = publickeyDescCreatedAt.Default.(func() time.Time)
	// publickeyDescUpdatedAt is the schema descriptor for updated_at field.
	publickeyDescUpdatedAt := publickeyFields[5].Descriptor()
	// publickey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	publickey.DefaultUpdatedAt = publickeyDescUpdatedAt.Default.(func() time.Time)
}
