// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// PrivateKey is the predicate function for privatekey builders.
type PrivateKey func(*sql.Selector)
